#!/bin/bash

if [ "$#" -lt 2 ];
then
  echo "Usage: $0 <build type> <build target>."
  exit 1
fi

cmake -DCMAKE_BUILD_TYPE="${1^}" -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S . -B cmake-build-"$1" &&
cmake --build cmake-build-"$1" --target "$2" -j 6
